### ISSUE TITLE
Warning: Unconfigured $PROJECT_DIRS despite it being set

### ISSUE THREAD

**Issue by moigagoo** [astronouth7303/xontrib-avox#1]
I have `$PROJECT_DIRS = ["~/Projects"]` in my .xonshrc, but avox seems to disregard that.

**Comment by AstraLuma** [comment]
Use `$PROJECT_DIRS = [os.path.expanduser"~/Projects")]`.

(The closest xonsh has to doing that conveniently for python is globbing.)

**Comment by AstraLuma** [comment]
(Also, if you just pulled from pip, I broke `avox new`/`avox create`. I'm going to try to do a fixed release tonight.)

**Comment by moigagoo** [comment]
Thanks!
